OnlineFoodDelivery/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as MarketplaceViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('accounts/',include('accounts.urls')),
    path('vendor/',include('vendor.urls')),
    path('marketplace/',include('marketplace.urls')),
    path('customer/',include('customers.urls')),
    path('orders/', include('orders.urls')),

    #CART
    path('cart/', MarketplaceViews.cart, name='cart'),

    #SEARCH
    path('search/',MarketplaceViews.search,name="search"),

    #CHECKOUT
    path('checkout/',MarketplaceViews.checkout,name="checkout"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "OnlineFoodDelivery.views.page_not_found_view"

accounts/urls.py
from django.urls import path,include,reverse
from . import views

app_name = 'accounts'

urlpatterns = [
    path('',views.myAccount,name="myAccount"),
    path('registerUser/',views.registerUser,name="registerUser"),
    path('registerVendor/',views.registerVendor,name="registerVendor"),
    path('login/',views.signin,name="signin"),
    path('logout/',views.signout,name="signout"),
    path('myAccount/',views.myAccount,name="myAccount"),
    path('customerDashboard/',views.customerDashboard,name="customerDashboard"),
    path('vendorDashboard/',views.vendorDashboard,name="vendorDashboard"),
    path('activate/<uidb64>/<token>/', views.activate,name="activate"),
    path('vendor/', include('vendor.urls')),

    #forgot password functionality
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
    path('reset_password/', views.reset_password, name='reset_password'),

]

customers/urls.py
from django.urls import path,include,reverse
from accounts import views as AccountViews
from . import views

app_name = 'customers'
urlpatterns = [
    path('',AccountViews.customerDashboard,name="customers"),
    path('profile/', views.profile, name='profile'),
    path('my-orders/', views.my_orders, name='my_orders'),
    path('order-detail/<int:order_number>/', views.order_detail, name='order_detail'),
    path('cancel-order/<int:order_number>/', views.cancel_order, name='cancel_order'),
]

orders/urls.py
from django.urls import path,include
from . import views

app_name = 'orders'
urlpatterns = [
    path('place_order/',views.place_order,name="place_order"),
    path('payment/',views.payment,name="payment"),
    path('order_complete/',views.order_complete,name="order_complete"),

]

accounts/forms.py
from django import forms
from .models import User,UserProfile
from .validators import allow_only_images_validator

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password','confirm_password']
    
    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError(
                "Password and Confirm Password does not match!"
            )
        
class UserProfileForm(forms.ModelForm):
        profile_picture = forms.FileField(widget=forms.FileInput(attrs={'class': 'btn btn-info'}),validators=[allow_only_images_validator])
        cover_photo = forms.FileField(widget=forms.FileInput(attrs={'class': 'btn btn-info'}),validators=[allow_only_images_validator])
        class Meta:
            model = UserProfile
            fields = ['profile_picture', 'cover_photo', 'address', 'country', 'state', 'city', 'pin_code', 'latitude', 'longitude']

        def __init__(self, *args, **kwargs):
            super(UserProfileForm, self).__init__(*args, **kwargs)
            for field in self.fields:
                if field == 'latitude' or field == 'longitude':
                    self.fields[field].widget.attrs['readonly'] = 'readonly'


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'phone_number']

accounts/views.py
import datetime
from django.shortcuts import render,redirect
from orders.models import Order
from .forms import UserForm
from .models import User,UserProfile
from django.contrib import messages, auth
from vendor.forms import VendorForm
from vendor.models import Vendor
from .utils import detectUser, send_verification_email
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.template.defaultfilters import slugify

# Restrict the vendor from accessing the customer page
def check_role_vendor(user):
    if user.role == 1:
        return True
    else:
        raise PermissionDenied


# Restrict the customer from accessing the vendor page
def check_role_customer(user):
    if user.role == 2:
        return True
    else:
        raise PermissionDenied
    
# Create your views here.
def registerUser(request):
    if request.user.is_authenticated:
        messages.warning(request,"You are already Logged in !")
        return redirect('accounts:myAccount')
    
    elif request.method == 'POST':
        form = UserForm(request.POST)
        
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            username = form.cleaned_data['username'] 
            password = form.cleaned_data['password']
            user = User.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email, password=password)
            user.role = User.CUSTOMER
            user.save()

            #send verification mail
            mail_subject = 'Please activate your account'
            mail_template = 'accounts/emails/account_verification_email.html'
            send_verification_email(request, user,mail_subject,mail_template)

            messages.success(request,"Great! You just created your account! check your mail to activate.")
            return redirect('accounts:signin')
        else:
            print(form.errors)   
    else:    
        form = UserForm()
    return render(request,'accounts/registerUser.html',{'form':form})

def registerVendor(request):
    if request.user.is_authenticated:
        messages.warning(request,"You are already Logged in !")
        return redirect('accounts:myAccount')
    
    elif request.method == 'POST':
        form = UserForm(request.POST)
        v_form = VendorForm(request.POST, request.FILES)
        if form.is_valid() and v_form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = User.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email, password=password)
            user.role = User.VENDOR
            vendor = v_form.save(commit=False)
            vendor.user = user
            vendor_name = v_form.cleaned_data['vendor_name']
            vendor.vendor_slug = slugify(vendor_name)+'-'+str(user.id)
            user_profile = UserProfile.objects.get(user=user)
            vendor.user_profile = user_profile
            user.save()
            vendor.save()
            
            #send verification mail
            mail_subject = 'Please activate your account'
            mail_template = 'accounts/emails/account_verification_email.html'
            send_verification_email(request, user,mail_subject,mail_template)
            
            messages.success(request, 'Your account has been registered sucessfully! Please check your mail to activate and wait for the approval.')
            return redirect('accounts:signin')
        else:
            print(form.errors)
            print(v_form.errors)
    
    else:
        form = UserForm()
        v_form = VendorForm()
    return render(request,'accounts/registerVendor.html',{'form':form,'v_form':v_form})

def signin(request):
    if request.user.is_authenticated:
        messages.warning(request,"You are already Logged in !")
        return redirect('accounts:myAccount')
    elif request.method=='POST':
        email=request.POST['e-mail']
        password=request.POST['password']
        user = auth.authenticate(email=email, password=password)
        if user is not None:
            # print('success')
            auth.login(request,user)
            messages.success(request,'You are now Logged in.')
            return redirect('accounts:myAccount')
        else:
            # print('fail')
            messages.error(request,'Invalid Login credentials')
            return redirect('accounts:signin')

    else:
        return render(request,"accounts/signin.html")

@login_required
def signout(request):
    auth.logout(request)
    messages.info(request, 'You are Logged out.')
    return redirect('accounts:signin')
    
@login_required
def myAccount(request):
    user = request.user
    redirectUrl = detectUser(user)
    return redirect(redirectUrl)

@login_required
@user_passes_test(check_role_customer)
def customerDashboard(request):
    orders = Order.objects.filter(user=request.user, is_ordered=True).order_by('-created_at')
    recent_orders = orders[:5]
    context = {
        'orders': orders,
        'orders_count': orders.count(),
        'recent_orders': recent_orders,
    }
    return render(request,'accounts/customerDashboard.html',context)

@login_required
@user_passes_test(check_role_vendor)
def vendorDashboard(request):
    vendor = Vendor.objects.get(user=request.user)
    orders = Order.objects.filter(vendors__in=[vendor.id], is_ordered=True).order_by('-created_at')
    recent_orders = orders[:5]

    #total revenue
    total_revenue = 0
    for i in orders:
        total_revenue += i.get_total_by_vendor()['grand_total']

    #current month revenue
    current_month = datetime.datetime.now().month
    current_month_orders = orders.filter(vendors__in=[vendor.id], created_at__month=current_month)
    current_month_revenue = 0
    for i in current_month_orders:
        current_month_revenue += i.get_total_by_vendor()['grand_total']
    
    context = {
        'user' : request.user,
        'orders': orders,
        'orders_count': orders.count(),
        'recent_orders' : recent_orders,
        'total_revenue':total_revenue,
        'current_month_revenue': current_month_revenue,
    }
    return render(request,'accounts/vendorDashboard.html',context)


def activate(request, uidb64, token):
    # Activate the user by setting the is_active status to True
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Congratulations! Your account is now activated.')
        return redirect('accounts:myAccount')
    else:
        messages.error(request, 'Invalid activation link')
        return redirect('accounts:myAccount')
    
def forgot_password(request):
    if request.method == 'POST':
        email = request.POST['email']

        if User.objects.filter(email=email).exists():
            user = User.objects.get(email__exact=email)

            # send reset password email
            mail_subject = 'Reset Your Password'
            email_template = 'accounts/emails/reset_password_email.html'
            send_verification_email(request, user, mail_subject, email_template)

            messages.success(request, 'Password reset link has been sent to your email address.')
            return redirect('accounts:signin')
        else:
            messages.error(request, 'Account does not exist')
            return redirect('accounts:forgot_password')
    return render(request, 'accounts/forgot_password.html')


def reset_password_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        messages.info(request, 'Please reset your password')
        return redirect('accounts:reset_password')
    else:
        messages.error(request, 'This link has been expired!')
        return redirect('accounts:myAccount')
    

def reset_password(request):
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            pk = request.session.get('uid')
            user = User.objects.get(pk=pk)
            user.set_password(password)
            user.is_active = True
            user.save()
            messages.success(request, 'Password reset successful')
            return redirect('accounts:signin')
        else:
            messages.error(request, 'Passwords do not match!')
            return redirect('accounts:reset_password')
    return render(request, 'accounts/reset_password.html')




    


    

templates/accounts/customerdashboard.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<!--ALERTS START-->

<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <!-- Load message -->
        {% include 'includes/alerts.html' %}
    </div>
</div>

<!--ALERTS END-->
<!-- Main Section Start -->
<div class="main-section">
    {% include 'customers/cover.html' %}
    <div class="page-section account-header buyer-logged-in">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    <!--sidebar start-->
                    {% include 'includes/custSidebar.html' %}
                    <!--side bar end-->
                </div>

                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                            <h5 class="text-uppercase">Overview</h5>
                            <div class="row">
                                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                    <div class="card">
                                        <div class="card-header">
                                            Total Orders
                                        </div>
                                        <div class="card-body text-center">
                                            <a href="#"><h5 class="card-title">{{ orders_count }}</h5></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                                    <div class="card">
                                        <div class="card-header">
                                            Logged in as: <b>{{ user.email }}</b>
                                        </div>
                                        <div class="card-body text-center">
                                            <a href="{% url 'customers:profile' %}"><h5 class="card-title"><i class="fa fa-edit"></i> Edit profile</h5></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br>
                            
                            <h5 class="text-uppercase">Recent Orders</h5>
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="user-orders-list">
                                        <div class="responsive-table">
                                            <table class="table table-hover" id="myOrdersTable">
                                                <thead>
                                                  <tr>
                                                    <th scope="col">Order #</th>
                                                    <th scope="col">Name</th>
                                                    <th scope="col">Total</th>
                                                    <th scope="col">Status</th>
                                                    <th scope="col">Date</th>
                                                    <th scope="col">Action</th>
                                                  </tr>
                                                </thead>
                                                <tbody>
                                                    {% for order in recent_orders %}
                                                  <tr>
                                                    <td>{{ order.order_number }}</td>
                                                    <td>{{ order.name }}</td>
                                                    <td>₹{{ order.total }}</td>
                                                    <td>{{ order.status }}</td>
                                                    <td>{{ order.get_ist_time }}</td>
                                                    <td><a href="{% url 'customers:order_detail' order.order_number %}" class="btn btn-danger">Details</a></td>
                                                  </tr>
                                                  {% endfor %}
                                                </tbody>
                                              </table>

                                        </div>												
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->
{% endblock %}

templates/accounts/forgot_password.html
{% extends 'base.html' %}

{% block content %}
<!-- Main Section Start -->
<div class="main-section">
    <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 60px;margin-bottom: 0px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="user-dashboard loader-holder" style="width: 450px; min-height: auto;">
                        <div class="user-holder">
                    <h4 class="text-center" style="margin-bottom: 0;">Forgot your password?</h4>
                    <p class="text-center">Please enter your email address and we will send you a link to reset your password.</p>
                    <hr>
                    <div id="restaurant-sets-holder">
                        <form action="{% url 'accounts:forgot_password' %}" class="form-fields-set foodbakery-dev-restaurant-form" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <ul class="register-add-restaurant-tab-container restaurant-information-tab-container">
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="row">
                                                
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Email Address</label>
                                                                <input type="email" name="email" placeholder="Enter your email address">
                                                            </div>
                                                        </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="field-holder">
                                                <div class="payment-holder">
                                                    <input type="submit" value="Continue" id="btn-next-restaurant-information" class="bgcolor">
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <!-- Load message -->
                                            {% include 'includes/alerts.html' %}
                                        </div>
                                    </div>

                                </li>
                            </ul>
                        </form>
                    </div>
                </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->
{% endblock %}

templates/accounts/registerUser.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="main-section">
    <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 60px;margin-bottom: 0px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                    <h4 class="text-center" style="margin-bottom: 0;">WELCOME TO FOODONLINE</h4>
                    <p class="text-center">Please fill this form to get yourself onboarded in the foodOnline marketplace.</p>
                    <hr>
                    
                    <!--ALERTS START-->
                    <center>
                        <ul class="errorlist">
                            {% for field in form %}
                                {% if field.errors %}
                                    {% for error in field.errors %}
                                        <li style="color: red;">{{error}}</li>
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}

                            <li style="color: red;">{{form.non_field_errors}}</li>
                        </ul>
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <!-- Load message -->
                                    {% if messages %}
                                        {% for message in messages %}
                                            <div class="alert alert-{{message.tags}} show-notification" role="alert">
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            <strong>{{message}}</strong>
                                            </div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </div>
                    </center>
                    <!--ALERTS END-->

                    <div id="restaurant-sets-holder">
                        <form action="{% url 'accounts:registerUser' %}" class="form-fields-set foodbakery-dev-restaurant-form" method="post" >
                            {% csrf_token %}
                            <ul class="register-add-restaurant-tab-container restaurant-information-tab-container">
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="row">
                                                <ul >
                                                    <li>
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>First name</label>{{form.first_name}}
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Last name</label>{{form.last_name}}
                                                            </div>
                                                        </div>
                                                        
                                                        
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Email Address</label>{{form.email}}
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Username</label>{{form.username}}
                                                            </div>
                                                        </div>
                                                    </li>
                                                    
                                                    <li>
                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Password</label>
                                                                {{form.password}}
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Confirm Password</label>
                                                                {{form.confirm_password}}
                                                            </div>
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="field-holder">
                                                <div class="payment-holder">
                                                    <input type="submit" value="Submit" id="btn-next-restaurant-information" class="bgcolor">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </form>
                    </div>
                </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}