OnlineFoodDelivery/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as MarketplaceViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('accounts/',include('accounts.urls')),
    path('vendor/',include('vendor.urls')),
    path('marketplace/',include('marketplace.urls')),
    path('customer/',include('customers.urls')),
    path('orders/', include('orders.urls')),

    #CART
    path('cart/', MarketplaceViews.cart, name='cart'),

    #SEARCH
    path('search/',MarketplaceViews.search,name="search"),

    #CHECKOUT
    path('checkout/',MarketplaceViews.checkout,name="checkout"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "OnlineFoodDelivery.views.page_not_found_view"

accounts/urls.py
from django.urls import path,include,reverse
from . import views

app_name = 'accounts'

urlpatterns = [
    path('',views.myAccount,name="myAccount"),
    path('registerUser/',views.registerUser,name="registerUser"),
    path('registerVendor/',views.registerVendor,name="registerVendor"),
    path('login/',views.signin,name="signin"),
    path('logout/',views.signout,name="signout"),
    path('myAccount/',views.myAccount,name="myAccount"),
    path('customerDashboard/',views.customerDashboard,name="customerDashboard"),
    path('vendorDashboard/',views.vendorDashboard,name="vendorDashboard"),
    path('activate/<uidb64>/<token>/', views.activate,name="activate"),
    path('vendor/', include('vendor.urls')),

    #forgot password functionality
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
    path('reset_password/', views.reset_password, name='reset_password'),

]

marketplace/urls.py
from django.urls import path,include
from . import views

app_name='marketplace'
urlpatterns = [
    path('',views.marketplace,name="marketplace"),
    path('<slug:vendor_slug>/', views.vendor_detail, name='vendor_detail'),
    # ADD TO CART
    path('add_to_cart/<int:food_id>/', views.add_to_cart, name='add_to_cart'),
    # DECREASE CART
    path('decrease_cart/<int:food_id>/', views.decrease_cart, name='decrease_cart'),
    #DELETE CART ITEM
    path('delete_cart/<int:cart_id>/', views.delete_cart, name='delete_cart'),
]

orders/urls.py
from django.urls import path,include
from . import views

app_name = 'orders'
urlpatterns = [
    path('place_order/',views.place_order,name="place_order"),
    path('payment/',views.payment,name="payment"),
    path('order_complete/',views.order_complete,name="order_complete"),

]

marketplace/models.py
from django.db import models
from accounts.models import User
from menu.models import FoodItem

# Create your models here.

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fooditem = models.ForeignKey(FoodItem, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def item_total_cost(self):
        return self.quantity * self.fooditem.price

    def __unicode__(self):
        return self.user

class Tax(models.Model):
    tax_type = models.CharField(max_length=20, unique=True)
    tax_percentage = models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tax Percentage (%)')
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'tax'

    def __str__(self):
        return self.tax_type

marketplace/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render,get_object_or_404,redirect
from django.db.models import Prefetch
from marketplace.context_processors import get_cart_counter, get_cart_amounts
from vendor.models import Vendor
from menu.models import Category,FoodItem
from .models import Cart
from django.contrib.auth.decorators import login_required
from vendor.models import OpeningHour
from datetime import date
from django.db.models import Q
from accounts.models import UserProfile
#GeoDjango
from django.contrib.gis.geos import GEOSGeometry
from django.contrib.gis.measure import D # ``D`` is a shortcut for ``Distance``
from django.contrib.gis.db.models.functions import Distance

from orders.forms import OrderForm
# Create your views here.


def marketplace(request):
    vendors = Vendor.objects.filter(is_approved=True,user__is_active=True)[:8]
    vendors_count = vendors.count()
    
    context = {
        'vendors':vendors,
        'vendors_count':vendors_count,
    }
    return render(request,'marketplace/listings.html',context)

def vendor_detail(request, vendor_slug):
    vendor = get_object_or_404(Vendor,vendor_slug=vendor_slug)
    categories = Category.objects.filter(vendor=vendor).prefetch_related(
        Prefetch(
            'fooditems',
            queryset = FoodItem.objects.filter(is_available=True)
        )
    )

    if request.user.is_authenticated:
        cart_items = Cart.objects.filter(user=request.user)
    else:
        cart_items = None

    # Check current day's opening hours.
    today_date = date.today()
    today = today_date.isoweekday()

    current_opening_hours = OpeningHour.objects.filter(vendor=vendor,day=today)
    opening_hours = OpeningHour.objects.filter(vendor=vendor).order_by('day','-from_hour')
    context={
        'vendor':vendor,
        'categories':categories,
        'cart_items':cart_items,
        'opening_hours': opening_hours,
        'current_opening_hours': current_opening_hours,
    }

    return render(request,'marketplace/vendor_detail.html',context)

def add_to_cart(request, food_id):
        if request.user.is_authenticated:
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                # Check if the food item exists
                try:
                    fooditem = FoodItem.objects.get(id=food_id)
                    # Check if the user has already added that food to the cart
                    try:
                        chkCart = Cart.objects.get(user=request.user, fooditem=fooditem)
                        # Increase the cart quantity
                        chkCart.quantity += 1
                        chkCart.save()
                        return JsonResponse({'status': 'Success', 'message': 'Increased the cart quantity','cart_counter': get_cart_counter(request), 'qty': chkCart.quantity, 'cart_amount': get_cart_amounts(request)})            
                    except:
                        chkCart = Cart.objects.create(user=request.user, fooditem=fooditem, quantity=1)
                        return JsonResponse({'status': 'Success', 'message': 'Added the food to the cart','cart_counter': get_cart_counter(request), 'qty': chkCart.quantity, 'cart_amount': get_cart_amounts(request) })
                except:
                    return JsonResponse({'status': 'Failed', 'message': 'This food does not exist!'})
            else:
                return JsonResponse({'status': 'Failed', 'message': 'Invalid request!'})
        
        else:
            return JsonResponse({'status': 'login_required', 'message': 'Please login to continue'})
        

def decrease_cart(request, food_id):
    if request.user.is_authenticated:
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            # Check if the food item exists
            try:
                fooditem = FoodItem.objects.get(id=food_id)
                # Check if the user has already added that food to the cart
                try:
                    chkCart = Cart.objects.get(user=request.user, fooditem=fooditem)
                    if chkCart.quantity > 1:
                        # decrease the cart quantity
                        chkCart.quantity -= 1
                        chkCart.save()
                    else:
                        chkCart.delete()
                        chkCart.quantity = 0
                    return JsonResponse({'status': 'Success', 'cart_counter': get_cart_counter(request), 'qty': chkCart.quantity, 'cart_amount': get_cart_amounts(request)})
                except:
                    return JsonResponse({'status': 'Failed', 'message': 'You do not have this item in your cart!'})
            except:
                return JsonResponse({'status': 'Failed', 'message': 'This food does not exist!'})
        else:
            return JsonResponse({'status': 'Failed', 'message': 'Invalid request!'})
        
    else:
        return JsonResponse({'status': 'login_required', 'message': 'Please login to continue'})
    
@login_required(login_url = 'accounts:signin')
def cart(request):
    cart_items = Cart.objects.filter(user=request.user).order_by('created_at')
    context = {
        'cart_items':cart_items,
    }
    return render(request,'marketplace/cart.html',context)


def delete_cart(request, cart_id):
    if request.user.is_authenticated:
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            try:
                # Check if the cart item exists
                cart_item = Cart.objects.get(user=request.user, id=cart_id)
                if cart_item:
                    cart_item.delete()
                    return JsonResponse({'status': 'Success', 'message': 'Cart item has been deleted!', 'cart_counter': get_cart_counter(request), 'cart_amount': get_cart_amounts(request)})
            except:
                return JsonResponse({'status': 'Failed', 'message': 'Cart Item does not exist!'})
        else:
            return JsonResponse({'status': 'Failed', 'message': 'Invalid request!'})

#searching restaurants
def search(request):
    if not 'address' in request.GET:
        return redirect('marketplace:marketplace')
    
    address = request.GET['address']
    latitude = request.GET['lat']
    longitude = request.GET['long']
    keyword = request.GET['keyword']
    radius = request.GET['radius']

    #Searching for restaurants with food items
    fetch_vendors_by_fooditems = FoodItem.objects.filter(food_title__icontains=keyword, is_available=True).values_list('vendor', flat=True)
    #Making it possible for searching food and vendor
    vendors = Vendor.objects.filter( Q(id__in=fetch_vendors_by_fooditems)| Q(vendor_name__icontains=keyword,is_approved=True,user__is_active=True) )

    #location based search
    if latitude and longitude and radius:
        pnt = GEOSGeometry('POINT(%s %s)' % (longitude, latitude))

        vendors = Vendor.objects.filter(Q(id__in=fetch_vendors_by_fooditems) | Q(vendor_name__icontains=keyword, is_approved=True, user__is_active=True),
            user_profile__location__distance_lte=(pnt, D(km=radius))).annotate(distance=Distance("user_profile__location", pnt)).order_by("distance")
        
        for v in vendors:
            v.kms = round(v.distance.km, 1)
        

    vendors_count = vendors.count()
    context={
        'vendors':vendors,
        'vendors_count':vendors_count,
        'source_location':address,
    }
    return render(request,'marketplace/listings.html',context)

@login_required(login_url='accounts:signin')
def checkout(request):
    cart_items = Cart.objects.filter(user=request.user ).order_by('created_at')
    cnt=0
    for item in cart_items:
        if item.fooditem.vendor.is_open():
            cnt+=1
    if cnt == 0:
        return redirect('marketplace:marketplace')
    user_profile = UserProfile.objects.get(user=request.user)
    default_values = {
        'first_name': request.user.first_name,
        'last_name': request.user.last_name,
        'phone': request.user.phone_number,
        'email': request.user.email,
        'address': user_profile.address,
        'country': user_profile.country,
        'state': user_profile.state,
        'city': user_profile.city,
        'pin_code': user_profile.pin_code,
    }
    form = OrderForm(initial=default_values)
    context = {
        'form': form,
        'cart_items': cart_items,
    }
   
    return render(request,'marketplace/checkout.html',context)

templates/marketplace/cart.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<!-- Main Section Start -->
<div class="main-section pt-5">
    <div class="page-section">
        <div class="container">
            <div class="row">
                
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <div class="tabs-holder horizontal">
                        <ul class="stickynav-tabs nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="#home"><i class="fa fa-shopping-cart text-danger"></i>Cart Items</a></li>
                            
                        </ul>
                        <div class="tab-content">
                            <div id="home" class="tab-pane in active">
                                <div class="menu-itam-holder">
                                    
                                    <div class="text-center p-5" id="empty-cart" style="display: none;">
                                        <h3>Cart is empty</h3>
                                    </div>

                                    <div id="menu-item-list-6272" class="menu-itam-list">
                                        
                                        <ul>
                                            {% if cart_items %}
                                                {% for item in cart_items %}
                                                    
                                                    <li id="cart-item-{{item.id}}">
                                                        {% if item.fooditem.vendor.is_open %}
                                                            <div class="image-holder"> <img src="{{ item.fooditem.image.url }}" alt=""></div>
                                                            <div class="text-holder">
                                                                <h6>{{ item.fooditem }}</h6>
                                                                <span>{{ item.fooditem.description }}</span>
                                                                <a href="{% url 'marketplace:vendor_detail' item.fooditem.vendor.vendor_slug %}" class="badge badge-warning">{{ item.fooditem.vendor }}</a>
                                                            </div>
                                                            <div class="price-holder">
                                                                <span class="price"><b>₹{{ item.fooditem.price }}</b></span>

                                                                <a href="#" class="decrease_cart" data-id="{{ item.fooditem.id }}" id="{{item.id}}" data-url="{% url 'marketplace:decrease_cart' item.fooditem.id %}" style="margin-right: 28px;"><i class="icon-minus text-color"></i></a>
                                                                <label id="qty-{{item.fooditem.id}}">0</label>
                                                                <a href="#" class="add_to_cart" data-id="{{ item.fooditem.id }}" data-url="{% url 'marketplace:add_to_cart' item.fooditem.id %}"><i class="icon-plus4 text-color"></i></a>
                                                                <a href="#" class="delete_cart" data-id="{{ item.id }}" data-url="{% url 'marketplace:delete_cart' item.id %} "><i class="icon-delete text-color"></i></a>
                                                                
                                                            </div>
                                                        
                                                        {% else %}
                                                        
                                                            <div class="image-holder"> <img src="{{ item.fooditem.image.url }}" alt=""></div>
                                                            <div class="text-holder">
                                                                <h6>{{ item.fooditem }}</h6>
                                                                <span>{{ item.fooditem.description }}</span>
                                                                <a href="{% url 'marketplace:vendor_detail' item.fooditem.vendor.vendor_slug %}" class="badge badge-warning">{{ item.fooditem.vendor }}</a>
                                                                <a href="#" class="badge badge-danger" >Closed right now</a>
                                                            </div>
                                                            <div class="price-holder">
                                                                <span class="price"><b>₹{{ item.fooditem.price }}</b></span>

                                                                <a href="#" class="disable_cart" data-id="#" id="{{item.id}}" data-url="#" style="margin-right: 28px;"><i class="icon-minus text-color"></i></a>
                                                                <label id="qty-{{item.fooditem.id}}">0</label>
                                                                <a href="#" class="disable_cart" data-id="#" data-url="#"><i class="icon-plus4 text-color"></i></a>
                                                                <a href="#" class="delete_cart" data-id="{{ item.id }}" data-url="{% url 'marketplace:delete_cart' item.id %} "><i class="icon-delete text-color"></i></a>
                                                                
                                                            </div>
                                                        {% endif %}
                                                    </li>
                                                    
                                                {% endfor %}
                                            {% else %}
                                                <div class="text-center p-5">
                                                    <h3>Cart is empty</h3>
                                                </div>
                                            {% endif %}
                                        </ul>
                                        
                                        
                                        
                                    </div>

                                    {% for item in cart_items %}

                                    <span id="qty-{{item.fooditem.id}}" class="item_qty d-none" data-qty="{{ item.quantity }}">{{ item.quantity }}</span>

                                    {% endfor %}
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>

                <!-- Your order section -->
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="tabs-holder horizontal">
                        <ul class="stickynav-tabs nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="#home"><i class="icon- icon-room_service"></i>Your Order</a></li>
                            
                        </ul>
                        <div class="tab-content">
                            <div id="home" class="tab-pane in active">
                                <div class="menu-itam-holder">
                                    
                                    <div>
                                        <ul>
                                            <li style="list-style-type: none;">
                                                Subtotal
                                                <span class="price float-right">
                                                    <span class="currency">₹</span>
                                                    <span id="subtotal">{{ subtotal }}</span>
                                                </span>
                                            </li>
                                            
                                            {% for key, value in tax_dict.items %}
                                                {% for i, j in value.items %}
                                                    <li style="list-style-type: none;">
                                                        {{ key }} <small>({{ i }}%)</small>
                                                        <span class="price float-right">
                                                            <span class="currency">₹</span>
                                                            <span id="tax-{{ key }}">{{ j }}</span>
                                                        </span>
                                                    </li>
                                                {% endfor %}
                                            {% endfor %}


                                            <li style="list-style-type: none; font-weight: 600;">
                                                TOTAL
                                                <span class="price float-right">
                                                    <span class="currency">₹</span>
                                                    <span id="total">{{ grand_total }}</span>
                                                </span>
                                            </li>

                                            <a href="{% url 'checkout' %}" class="btn btn-danger w-100 p-2 mt-3">PROCEED TO CHECKOUT</a>
                                        </ul>
                                    </div>
                                    
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->

{% endblock %}

templates/marketplace/listings.html
{% extends 'base.html' %}

{% block content  %}
{% load static %}

<!-- Main Section Start -->
<div class="main-section">
    <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 10px;margin-bottom: 0px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="row">
                        <aside class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                            
                        </aside>
                        <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">
                            <div class="listing-sorting-holder">
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <h4>{% if vendors_count %}{{vendors_count}}{% else %}No{% endif %} Restaurants found</h4>
                                    </div>
                                </div>
                            </div>
                            <div class="listing simple">
                                <ul>
                                    {% for vendor in vendors %}
                                        <li style="line-height: 15px;">
                                            <div class="img-holder">
                                                <figure>
                                                    {% if vendor.user_profile.profile_picture %}
                                                        <a href="#"><img src="{{ vendor.user_profile.profile_picture.url}}" class="img-list wp-post-image" alt="Profile Image" ></a>
                                                    {% else %}
                                                        <a href="#"><img src="{% static 'extra-images/default-profile.jpg' %}" class="img-list wp-post-image" alt="Profile Image"></a>
                                                    {% endif %}    
                                                </figure>
                                                {% if vendor.is_open %}
                                                <span class="restaurant-status Open"><em class="bookmarkRibbon"></em>Open</span>
                                                {% else %}
                                                <span class="restaurant-status close"><em class="bookmarkRibbon"></em>Close</span>
                                                {% endif %}
                                            </div>
                                            <div class="text-holder">
                                                
                                                <div class="post-title">
                                                    <h5>
                                                        <a href="{% url 'marketplace:vendor_detail' vendor.vendor_slug %}">{{vendor}}</a>
                                                    </h5>
                                                </div>
                                                {% if vendor.user_profile.address %}
                                                    <span><small class="text-muted">{{ vendor.user_profile.address }}</small></span>
                                                {% endif %}
                                                
                                                <br>
                                                {% if source_location %}
                                                    <span><small><b>{{vendor.kms}}km</b> away from {{source_location}}</small></span>
                                                {% endif %}

                                            </div>
                                            <div class="list-option">

                                                <a href="{% url 'marketplace:vendor_detail' vendor.vendor_slug %}" class="viewmenu-btn text-color">View Menu</a>
                                            </div>
                                        </li>
                                    {% endfor %}

                                </ul>
                            </div>
                            
                        </div>
                        {% if not user.is_authenticated %}
                        <div class="section-sidebar col-lg-3 col-md-3 col-sm-12 col-xs-12">
                            <div class="message-box" style="background-color: #fa9918;">
                                <strong>I'm not Listed!</strong><span>is your restaurant or
                                    business not
                                    listed on over site</span>
                                <a href="{% url 'accounts:registerVendor' %}" class="request-btn">Add Your business!</a>
                            </div>
                        </div>
                        {% endif %}


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->

{% endblock  %}