OnlineFoodDelivery/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as MarketplaceViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('accounts/',include('accounts.urls')),
    path('vendor/',include('vendor.urls')),
    path('marketplace/',include('marketplace.urls')),
    path('customer/',include('customers.urls')),
    path('orders/', include('orders.urls')),

    #CART
    path('cart/', MarketplaceViews.cart, name='cart'),

    #SEARCH
    path('search/',MarketplaceViews.search,name="search"),

    #CHECKOUT
    path('checkout/',MarketplaceViews.checkout,name="checkout"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "OnlineFoodDelivery.views.page_not_found_view"

accounts/urls.py
from django.urls import path,include,reverse
from . import views

app_name = 'accounts'

urlpatterns = [
    path('',views.myAccount,name="myAccount"),
    path('registerUser/',views.registerUser,name="registerUser"),
    path('registerVendor/',views.registerVendor,name="registerVendor"),
    path('login/',views.signin,name="signin"),
    path('logout/',views.signout,name="signout"),
    path('myAccount/',views.myAccount,name="myAccount"),
    path('customerDashboard/',views.customerDashboard,name="customerDashboard"),
    path('vendorDashboard/',views.vendorDashboard,name="vendorDashboard"),
    path('activate/<uidb64>/<token>/', views.activate,name="activate"),
    path('vendor/', include('vendor.urls')),

    #forgot password functionality
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
    path('reset_password/', views.reset_password, name='reset_password'),

]

customers/urls.py
from django.urls import path,include,reverse
from accounts import views as AccountViews
from . import views

app_name = 'customers'
urlpatterns = [
    path('',AccountViews.customerDashboard,name="customers"),
    path('profile/', views.profile, name='profile'),
    path('my-orders/', views.my_orders, name='my_orders'),
    path('order-detail/<int:order_number>/', views.order_detail, name='order_detail'),
    path('cancel-order/<int:order_number>/', views.cancel_order, name='cancel_order'),
]

marketplace/urls.py
from django.urls import path,include
from . import views

app_name='marketplace'
urlpatterns = [
    path('',views.marketplace,name="marketplace"),
    path('<slug:vendor_slug>/', views.vendor_detail, name='vendor_detail'),
    # ADD TO CART
    path('add_to_cart/<int:food_id>/', views.add_to_cart, name='add_to_cart'),
    # DECREASE CART
    path('decrease_cart/<int:food_id>/', views.decrease_cart, name='decrease_cart'),
    #DELETE CART ITEM
    path('delete_cart/<int:cart_id>/', views.delete_cart, name='delete_cart'),
]

orders/urls.py
from django.urls import path,include
from . import views

app_name = 'orders'
urlpatterns = [
    path('place_order/',views.place_order,name="place_order"),
    path('payment/',views.payment,name="payment"),
    path('order_complete/',views.order_complete,name="order_complete"),

]

templates/includes/alerts.html
{% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{message.tags}} show-notification" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                    <strong>{{message}}</strong>
            </div>
        {% endfor %}
{% endif %}

templates/includes/cover.html
{% load static %}
<div class="page-section restaurant-detail-image-section" style=" background: url({% if vendor.user_profile.cover_photo %} {{ vendor.user_profile.cover_photo.url }} {% else %} {% static 'extra-images/default-cover.jpg' %}{% endif %}) no-repeat scroll 0 0 / cover;">
    <!-- Container Start -->
    <div class="container">
        <!-- Row Start -->
        <div class="row">
            <!-- Column Start -->
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="company-info-detail">
                    <div class="company-info">
                        <div class="img-holder">
                            <figure>
                                {% if vendor.user_profile.profile_picture %}
                                <img src="{{ vendor.user_profile.profile_picture.url }}" alt="">
                                {% else %}
                                <img src="{% static 'extra-images/default-profile.jpg' %}" alt="">
                                {% endif %}
                            </figure>
                        </div>

                        <div class="text-holder">
                            <span class="restaurant-title">{{vendor.vendor_name}}</span>
                            <div class="text">
                                {% if vendor.user_profile.address %}
                                <i class="icon-location"></i>
                                <p>{{vendor.user_profile.address}}</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Column End -->
        </div>
        <!-- Row End -->
    </div>
    <!-- Container End -->
</div>

templates/includes/custSidebar.html
<div class="user-account-nav user-account-sidebar">
    <div class="user-nav-list">
        <ul>
            <li class="{% if '/accounts/customerDashboard/' == request.path or '/customer/' == request.path %}active{% endif %}"><a href="{% url 'accounts:myAccount' %}"><i class="icon-dashboard3"></i>Dashboard</a></li>
            <li class="{% if '/customer/my-orders/' == request.path or 'order-detail' in request.path  %}active{% endif %}"><a href="{% url 'customers:my_orders' %}"><i class="icon-add_shopping_cart"></i>My Orders</a></li>
       
            <li class="{% if '/customer/profile/' == request.path %}active{% endif %}"><a href="{% url 'customers:profile' %}"><i class="icon-build"></i>Profile Settings</a></li>
    
            <li><a class="logout-btn" href="{% url 'accounts:signout' %}"><i class="icon-log-out"></i>Signout</a></li>
        </ul>
    </div>
</div>

templates/includes/footer.html
{% load static %}
<!-- Footer Start -->
<footer id="footer" class="footer-style-2">
    <div class="footer-widget">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="widget widget-newsletter">
                        <div class="widget-title">
                            <h5>Subscribe to our Newsletter</h5>
                        </div>
                        <div class="fieldset">
                            <form action="#">
                                <div class="field-holder">
                                    <label>
                                        <i class=" icon-envelope3"></i>
                                        <input type="text" class="field-input" placeholder=" Enter Your Email Address...">
                                    </label>
                                </div>
                                <div class="field-holder btn-holder">
                                    <input class="subscribe-btn bgcolor" type="submit" value="Sign Up">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright-sec">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="copyright-inner">
                        <div class="copy-right">
                            <p>© 2023 Foodbakery. All Rights Reserved. Developed By <a href="#">Venkatesh</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- /.cs-copyright -->
</footer>
<!-- Footer End -->
</div>

<!-- Modal Popup End -->
<script src="{%static 'js/scripts.js'%}"></script>
<script src="{%static 'js/functions.js'%}"></script>
</body>

</html>

templates/includes/navbar.html
{% load static %}
<!--Main Wrapper-->
<div class="wrapper">
    <!-- Header Start -->
    <header id="header">
        <div class="main-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                        <div class="logo">
                            <figure>
                                <a href="{% url 'home' %}" class="light-logo">
                                    <img src="{%static 'logo/foodOnlineLogo.png'%}" width="250px" alt="OnlineFoodDelivery">
                                </a>
                            </figure>
                        </div>
                        
                        
                        <div class="main-location ml-5">
                            <ul>
                                <li class="location-has-children choose-location">
                                    <form action="#">
                                        <input type="text" value="" name="location" id="location" placeholder="Your current location" autocomplete="off">
                                        <span id="foodbakery_radius_location_open" class="foodbakery-radius-location" onclick="getLocation()"><i class="icon-target5"></i></span>
                                    </form>
                                    
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <div class="login-option">
                            {% if user.is_authenticated %}
                            <a href="{% url 'cart' %}">
                                <i class="fa fa-shopping-cart text-danger" style="font-size: 20px; margin-top:15px;"></i>
                                <span class="badge badge-warning" id="cart_counter" style="border-radius: 50px; position: relative; bottom:10px; left: -5px;">{{cart_count}}</span>
                            </a>
                            {% endif %}
                            <a href="{% url 'marketplace:marketplace' %}" class="btn btn-outline-danger text-uppercase font-weight-bold" style="height:28px !important; padding:2px 1.75em !important;" >Marketplace</a>
                            {% if user.is_authenticated %}
                                <a class="cs-color cs-popup-joinus-btn btn btn-light font-weight-bold text-uppercase " href="{% url 'accounts:myAccount' %}">My Account</a>
                                <a class="cs-popup-joinus-btn btn btn-danger text-white font-weight-bold text-uppercase" href="{% url 'accounts:signout' %}">Logout</a> 

                            {% else %}
                                <a class="cs-color cs-popup-joinus-btn login-popup " href="{% url 'accounts:signin' %}">Login</a> / <a class="cs-color cs-popup-joinus-btn login-popup ml-0" data-toggle="modal" href="{% url 'accounts:registerUser' %}">Register</a>
                                <a class="get-start-btn" href="{% url 'accounts:registerVendor' %}">Register Restaurant</a>

                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header End -->

    <script>
        var x = document.getElementById("location");

        //if page loaded in same session or came back to previous page
        //getting session item
        var current_location = sessionStorage.getItem("current_location")
        if(current_location != ""){
            x.value = current_location;
        }
        
        function getLocation()
        {
            
            if (navigator.geolocation)
            {
                navigator.geolocation.getCurrentPosition(showPosition);
            } 
            else
            { 
                x.innerHTML = "Geolocation is not supported by this browser.";
            }
        }
        
        function showPosition(position)
        {
            lat = position.coords.latitude;
            long = position.coords.longitude;
            
            // hit AJAX request to googlemaps api endpoint and get the location data using those lat and lng
            var GOOGLE_API_KEY = "{{ GOOGLE_API_KEY }}"
            var url = "https://maps.googleapis.com/maps/api/geocode/json?latlng="+lat+","+long+"+&key="+GOOGLE_API_KEY

            $.ajax({
                url: url,
                type: "GET",
                success: function(response){
                    var current_location = response.results[0].formatted_address;
                    console.log(current_location);
                    x.value = current_location;
                    //setting value to current_location in same session
                    sessionStorage.setItem("current_location", current_location)
                    window.location = '?lat='+lat+'&long='+long
            }
            })
        }
    </script>

templates/includes/vendSidebar.html
<div class="user-account-nav user-account-sidebar">
    <div class="user-nav-list">
        <ul>
            <li class="{% if '/accounts/vendorDashboard/' == request.path or '/accounts/vendor/' == request.path %}active{% endif %}"><a href="{% url 'accounts:myAccount' %}"><i class="icon-dashboard3"></i>Dashboard</a></li>
            <li class="{% if 'profile' in request.path %}active{% endif %}"><a href="{% url 'vendor:profile' %}"><i class="icon-building"></i>My Restaurant</a></li>
            <li class="{% if 'menu-builder' in request.path %}active{% endif %}" ><a href="{% url 'vendor:menu-builder'%}"><i class="icon-menu5"></i>Menu Builder</a></li>
            <li class="{% if 'opening-hours' in request.path %}active{% endif %}" ><a href="{% url 'vendor:opening_hours' %}"><i class="icon-menu5"></i>Opening Hours</a></li>
            <li class="{% if '/vendor/my-orders/' == request.path or 'order_detail' in request.path %}active{% endif %}"><a href="{% url 'vendor:my_orders' %}"><i class="icon-add_shopping_cart"></i>Orders</a></li>
            {% comment %} <li><a href="restaurant-earnings.html"><i class="icon-money"></i>Earnings</a></li> {% endcomment %}
            
            
            <li><a class="logout-btn" href="{% url 'accounts:signout' %}"><i class="icon-log-out"></i>Signout</a></li>
        </ul>
    </div>
</div>