OnlineFoodDelivery/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as MarketplaceViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('accounts/',include('accounts.urls')),
    path('vendor/',include('vendor.urls')),
    path('marketplace/',include('marketplace.urls')),
    path('customer/',include('customers.urls')),
    path('orders/', include('orders.urls')),

    #CART
    path('cart/', MarketplaceViews.cart, name='cart'),

    #SEARCH
    path('search/',MarketplaceViews.search,name="search"),

    #CHECKOUT
    path('checkout/',MarketplaceViews.checkout,name="checkout"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "OnlineFoodDelivery.views.page_not_found_view"

marketplace/urls.py
from django.urls import path,include
from . import views

app_name='marketplace'
urlpatterns = [
    path('',views.marketplace,name="marketplace"),
    path('<slug:vendor_slug>/', views.vendor_detail, name='vendor_detail'),
    # ADD TO CART
    path('add_to_cart/<int:food_id>/', views.add_to_cart, name='add_to_cart'),
    # DECREASE CART
    path('decrease_cart/<int:food_id>/', views.decrease_cart, name='decrease_cart'),
    #DELETE CART ITEM
    path('delete_cart/<int:cart_id>/', views.delete_cart, name='delete_cart'),
]

orders/urls.py
from django.urls import path,include
from . import views

app_name = 'orders'
urlpatterns = [
    path('place_order/',views.place_order,name="place_order"),
    path('payment/',views.payment,name="payment"),
    path('order_complete/',views.order_complete,name="order_complete"),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager
from django.db.models.fields.related import ForeignKey, OneToOneField


#postgis
from django.contrib.gis.db import models as gismodels
from django.contrib.gis.geos import Point

# Create your models here.
class UserManager(BaseUserManager): #this only contain methods
    def create_user(self,first_name,last_name,username,email,password=None):
        if not email:
            raise ValueError("user must possess email")
        if not username:
            raise ValueError("user must have username")
        
        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self,first_name,last_name,username,email,password=None):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
            first_name = first_name,
            last_name = last_name,
        )

        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser): #this only contain fields and calls methods
    VENDOR = 1
    CUSTOMER = 2

    ROLE_CHOICE = (
        (VENDOR, 'Vendor'),
        (CUSTOMER, 'Customer'),
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=12, blank=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICE, blank=True, null=True)

    # required fields
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = UserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True
    
    def get_role(self):
        if self.role == 1:
            user_role = 'Vendor'
        elif self.role == 2:
            user_role = 'Customer'
        return user_role

class UserProfile(models.Model):
    user = OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    profile_picture = models.ImageField(upload_to='users/profile_pictures', blank=True, null=True)
    cover_photo = models.ImageField(upload_to='users/cover_photos', blank=True, null=True)
    address = models.CharField(max_length=250, blank=True, null=True)
    country = models.CharField(max_length=15, blank=True, null=True)
    state = models.CharField(max_length=15, blank=True, null=True)
    city = models.CharField(max_length=15, blank=True, null=True)
    pin_code = models.CharField(max_length=6, blank=True, null=True)
    latitude = models.CharField(max_length=20, blank=True, null=True)
    longitude = models.CharField(max_length=20, blank=True, null=True)
    location = gismodels.PointField(blank=True, null=True, srid=4326)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.email
    
    def save(self, *args, **kwargs):
        if self.latitude and self.longitude:
            self.location = Point(float(self.longitude), float(self.latitude))
            return super(UserProfile, self).save(*args, **kwargs)
        return super(UserProfile, self).save(*args, **kwargs)

orders/models.py
from datetime import datetime
from django.db import models

from accounts.models import User
from menu.models import FoodItem
from vendor.models import Vendor
import simplejson as json

#time related operations
import pytz

# Create your models here.

request_object = ''
class Payment(models.Model):
    PAYMENT_METHOD = (
        ('PayPal', 'PayPal'),
        ('RazorPay', 'RazorPay'), # Only for Indian Students.
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    transaction_id = models.CharField(max_length=100)
    payment_method = models.CharField(choices=PAYMENT_METHOD, max_length=100)
    amount = models.CharField(max_length=10)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.transaction_id


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    vendors = models.ManyToManyField(Vendor, blank=True)
    order_number = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15, blank=True)
    email = models.EmailField(max_length=50)
    address = models.CharField(max_length=200)
    country = models.CharField(max_length=15, blank=True)
    state = models.CharField(max_length=15, blank=True)
    city = models.CharField(max_length=50)
    pin_code = models.CharField(max_length=10)
    total = models.FloatField()
    tax_data = models.JSONField(blank=True, help_text = "Data format: {'tax_type':{'tax_percentage':'tax_amount'}}",null=True)
    total_data = models.JSONField(blank=True, null=True)
    total_tax = models.FloatField()
    payment_method = models.CharField(max_length=25)
    status = models.CharField(max_length=15, choices=STATUS, default='New')
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Concatenate first name and last name
    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'
    
    def order_placed_to(self):
        return ", ".join([str(i) for i in self.vendors.all()])
    
    def get_ist_time(self):
        order = Order.objects.get(pk=self.pk)     
        # print(order)
        # Get the order's created_at datetime in UTC
        created_at_utc = order.created_at.replace(tzinfo=pytz.UTC)
        # print(created_at_utc)
        # Convert the UTC datetime to IST
        ist_tz = pytz.timezone('Asia/Kolkata')
        created_at_ist = created_at_utc.astimezone(ist_tz)
        # print(created_at_ist)

        # Remove the timezone offset
        created_at_without_offset = created_at_ist.replace(tzinfo=None)
        return created_at_without_offset
    
    def get_total_by_vendor(self):
        vendor = Vendor.objects.get(user=request_object.user)
        subtotal = 0
        tax = 0
        tax_dict = {}
        if self.total_data:
            total_data = json.loads(self.total_data)
            #print(total_data)
            data = total_data.get(str(vendor.id))
            
            
            for key, val in data.items():
                subtotal += float(key)
                val = val.replace("'", '"')
                val = json.loads(val)
                tax_dict.update(val)

                # calculate tax
                # {'CGST': {'9.00': '6.03'}, 'SGST': {'7.00': '4.69'}}
                for i in val:
                    for j in val[i]:
                        tax += float(val[i][j])
        
        grand_total = float(subtotal) + float(tax)
        #print("grand_total =>",grand_total)
        context = {
            'subtotal': subtotal,
            'tax_dict': tax_dict, 
            'grand_total': grand_total,
        }
        return context
    
    def is_cancelable(self):
        order = Order.objects.get(pk=self.pk)     
        # print(order)
        # Get the order's created_at datetime in UTC
        created_at_utc = order.created_at.replace(tzinfo=pytz.UTC)

        # Convert the UTC datetime to IST
        ist_tz = pytz.timezone('Asia/Kolkata')
        created_at_ist = created_at_utc.astimezone(ist_tz)

        # Remove the timezone offset
        created_at_without_offset = created_at_ist.replace(tzinfo=None)


        ordered_time = created_at_without_offset
        present_time = datetime.now()
        # print("Ordered Time:", created_at_without_offset)
        # print("Present Time:", present_time)
        timediff = present_time - ordered_time
        # print("Time Difference:", timediff)
        tsecs = timediff.total_seconds()
        tmins = tsecs/60
        # print("Time Difference in Minutes:", tmins)
        cancel = None
        if tmins>0 and tmins<10:
            cancel = True
        else:
            cancel = False
        # print("Cancel Decision:", cancel)
        return cancel

    def __str__(self):
        return self.order_number


class OrderedFood(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fooditem = models.ForeignKey(FoodItem, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.fooditem.food_title

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>FoodOnline</title>
	<!-- Google Font Family Link Start -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800">
	<!-- Google Font Family Link End -->

	<!-- CSS -->
	<link rel="stylesheet" href="{% static 'css/iconmoon.css' %}" >
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'css/cs-foodbakery-plugin.css' %}" >
	<link rel="stylesheet" href="{% static 'css/bootstrap-slider.css' %}" >
	<link rel="stylesheet" href="{% static 'css/custom.css' %}" >
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">	
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<!-- JAVASCRIPT -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="{% static 'js/modernizr.js'%}"></script>
	<script src="{% static 'js/bootstrap.js'%}"></script>
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	{% if '/' == request.path or 'profile' in request.path %}
	<script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places&callback=initAutoComplete" defer></script>
	{% endif %}
	<script src="{% static 'js/custom.js' %}"></script>

	{% if 'place_order' in request.path %}
	<!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id={{ PAYPAL_CLIENT_ID }}&currency=USD"></script>
	{% endif %}
	
	<!-- Include Datatables plugin script and css -->
	<link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
	<script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
	<script>
		$(document).ready( function () {
			$('#ordersTable').DataTable();
		} );
	</script>

	<style>
		body, .main-section p, .mce-content-body p{
			font:Normal  14px/24px "Open Sans", sans-serif;letter-spacing: 0px;text-transform: none;color: #515151 !important;
		}

		.ribbon {
			position: absolute;
			right: -5px;
			top: -5px;
			z-index: 1;
			overflow: hidden;
			width: 93px;
			height: 93px;
			text-align: right;
		  }
		  .ribbon span {
			font-size: 0.8rem;
			color: #fff;
			text-transform: uppercase;
			text-align: center;
			font-weight: bold;
			line-height: 32px;
			transform: rotate(45deg);
			width: 125px;
			display: block;
			background: #79a70a;
			background: linear-gradient(#9bc90d 0%, #79a70a 100%);
			box-shadow: 0 3px 10px -5px rgba(0, 0, 0, 1);
			position: absolute;
			top: 17px; // change this, if no border
			right: -29px; // change this, if no border
		  }
		  
		  .ribbon span::before {
			 content: '';
			 position: absolute; 
			 left: 0px; top: 100%;
			 z-index: -1;
			 border-left: 3px solid #79A70A;
			 border-right: 3px solid transparent;
			 border-bottom: 3px solid transparent;
			 border-top: 3px solid #79A70A;
		  }
		  .ribbon span::after {
			 content: '';
			 position: absolute; 
			 right: 0%; top: 100%;
			 z-index: -1;
			 border-right: 3px solid #79A70A;
			 border-left: 3px solid transparent;
			 border-bottom: 3px solid transparent;
			 border-top: 3px solid #79A70A;
		  }
		  
		  .red span {
			background: linear-gradient(#f70505 0%, #8f0808 100%);
		  }
		  .red span::before {
			border-left-color: #8f0808;
			border-top-color: #8f0808;
		  }
		  .red span::after {
			border-right-color: #8f0808;
			border-top-color: #8f0808;
		  }
	</style>
	
</head>

<body>
    <!--NAVBAR HERE-->
        {%include 'includes/navbar.html'%}
    <!--CONTENT HERE -->
        {% block content%}
            <!-- content loading -->
        {% endblock %}

    <!--FOOTER HERE-->
        {%include 'includes/footer.html'%}
	
	
	

templates/home.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

	<!-- Main Section Start -->
	<div class="main-section">
		<!-- Home Pages Elements Strat -->
		<!-- Main Search Start -->
		<div class="page-section nopadding cs-nomargin" style="padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; background: url({% static 'extra-images/bg-image1.jpg' %}) no-repeat center / cover;">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
						<div class="element-title">
							<h1 style="font-size: 40px; color:rgb(255, 0, 0) !important; text-transform: uppercase; line-height: 50px; margin-bottom: 25px; text-align:center;">
								We are in the business of food<br>our restaurants do</h1>
							<p style="font-size: 18px; letter-spacing: 1px; color: #505050; text-align:center;">
								The best food items in the world, Try to bring delicious meals straight to your door.</p>
						</div>
					</div>
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
						<div class="main-search fancy bg-holder">
							<form method="GET" action="{% url 'search' %}">
								<div class="row">
									<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12">
										<div class="field-holder">
											<input name="keyword" type="text" placeholder="Resturant name or Food name">
										</div>
									</div>
									<div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
										<div class="field-holder">
											<ul>
												<li class="select-location">
													<div class="foodbakery-locations-fields-group foodbakery-focus-out">
														<span class="foodbakery-search-location-icon"><i class="icon-location"></i></span>
														<input type="text" id="id_address" name="address" class="location-field-text filter" placeholder="All Locations" required>
														<input type="hidden" id="id_latitude" value="" name="lat">
														<input type="hidden" id="id_longitude" value="" name="long">
													</div>
												</li>
											</ul>
										</div>
									</div>
									<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
										<select name="radius" id="radius" style="height: 50px;" required>
											<option value="" selected>Choose Radius</option>
											<option value="5">5km</option>
											<option value="10">10km</option>
											<option value="15">15km</option>
											<option value="25">25km</option>
										</select>
									</div>
									<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
										<div class="field-holder">
											<input type="submit" value="Search">
										</div>
									</div>
								</div>
							</form>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		<!-- Main Search End -->
		
		<!-- Nearby Restarurants Section Start -->
		<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 0px;margin-bottom: 0px;background: #ffffff;">
			<div class="container" >
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="element-title align-left">
							<h2>Nearby Restaurants</h2>
							<p>Explore restaurants, bars, and cafes near to you</p>
						</div>
					</div>
					
							{% for vendor in vendors %}
									<div class="col-2.5" style="margin-left:20px !important; margin-bottom:20px !important;">
										<div class="card" style="width: 15rem !important;">
											{% if vendor.is_open %}
												<div class="ribbon"><span>Open</span>
												</div>
											{% else %}
												<div class="ribbon red"><span>Close</span>
												</div>
											{% endif %}
											<center>
											{% if vendor.user_profile.profile_picture %}
												<a href="{% url 'marketplace:vendor_detail' vendor.vendor_slug %}"><img src="{{ vendor.user_profile.profile_picture.url }}" height="125" style="margin-top:20px;" class="attachment-full size-full wp-post-image" alt=""></a>
											{% else %}
												<a href="{% url 'marketplace:vendor_detail' vendor.vendor_slug %}"><img src="{% static 'extra-images/default-profile.jpg' %}" height="125" style="margin-top:20px;" class="attachment-full size-full wp-post-image" alt=""></a>
											{% endif %}
											</center>
											<div class="card-body">
												<center>
													<div class="card-title">
													<h5>
														<a href="{% url 'marketplace:vendor_detail' vendor.vendor_slug %}">{{vendor.vendor_name}}</a>
													</h5>
													</div>
													<address>
														{% if vendor.user_profile.city and vendor.user_profile.state and vendor.user_profile.pin_code %}
															<span>{{ vendor.user_profile.city }}, {{ vendor.user_profile.state }}, {{ vendor.user_profile.pin_code }}</span>
														
															{% endif %}
													</address>
												{% if vendor.kms %}
													<p class="card-text"><small><b>{{vendor.kms}} kms </b>away</small></p>
												{% endif %}
												</center>
												
											</div>
										</div>
									</div>
									
							{% endfor %}
					
				</div>
			</div>
		</div>
		<!-- Top Restarurants Section End -->
		<!-- Choose From Most Popular Listin Start -->
		<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="element-title align-left">
							<h2>Most Popular Restaurants</h2>
							<p>Order from the most popular resturants in your locality</p>
						</div>
					</div>
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="listing fancy">
							<ul class="row">
								{% for vendor,count in popular_vendors.items %}
									<li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
										<div class="list-post featured">
											<div class="img-holder">
												{% if vendor.user_profile.profile_picture %}
												<figure><a href="#"><img src="{{ vendor.user_profile.profile_picture.url }}" class="img-thumb wp-post-image" alt=""></a></figure>
												{% else %}
												<figure><a href="#"><img src="{% static 'extra-images/default-profile.jpg' %}" class="img-thumb wp-post-image" alt=""></a></figure>
												{% endif %}
												
												{% if vendor.is_open %}
												<span class="restaurant-status open">
													<em class="bookmarkRibbon"></em>Open
												</span>
												{% else %}
												<span class="restaurant-status close"><em class="bookmarkRibbon"></em>Close</span>
												{% endif %}

											</div>
											<div class="text-holder">
												<div class="post-title">
													<h5>
														<a href="{% url 'marketplace:vendor_detail' vendor.vendor_slug %}">{{ vendor }}</a>
														
													</h5>
												</div>
												<address>
													{% if vendor.user_profile.city and vendor.user_profile.state and vendor.user_profile.pin_code %}
														<span>{{ vendor.user_profile.city }}, {{ vendor.user_profile.state }}, {{ vendor.user_profile.pin_code }}</span>
													
														{% endif %}
												</address>
												<p > Orders served : <b>{{count}}</b></p>
											</div>
											
										</div>
									</li>
								{% endfor %}
								
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Choose From Most Popular Listing End -->

		<!-- Home Pages Elements End  -->
	</div>
	<!-- Main Section End -->
{% endblock %}